export const CREATE_SUBJECTIVE = "CREATE_SUBJECTIVE";
export const RETRIEVE_SUBJECTIVE_QUESTIONS = "RETRIEVE_SUBJECTIVE_QUESTIONS";
export const UPDATE_SUBJECTIVE = "UPDATE_SUBJECTIVE";
export const DELETE_SUBJECTIVE = "DELETE_SUBJECTIVE";
//export const DELETE_ALL_SUBJECTIVE = "DELETE_ALL_SUBJECTIVE";


export const CREATE_OBJECTIVE = "CREATE_OBJECTIVE";
export const RETRIEVE_OBJECTIVE_QUESTIONS = "RETRIEVE_OBJECTIVE_QUESTIONS";
export const UPDATE_OBJECTIVE = "UPDATE_OBJECTIVE";
export const DELETE_OBJECTIVE = "DELETE_OBJECTIVE";